name: CI / Password Manager

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build-variant:
        description: "Build Variant"
        required: true
        default: "Beta"
        type: choice
        options:
          - Beta
          - Production
      build-mode:
        description: "Build Mode"
        required: true
        default: "Device"
        type: choice
        options:
          - Device
          - Simulator
      version-name:
        description: "Version Name Override - e.g. '2024.8.1'"
        type: string
      version-number:
        description: "Version Number Override - e.g. '1021'"
        type: string
      compiler-flags:
        description: "Compiler Flags - e.g. 'DEBUG_MENU FEATURE2'"
        type: string
      patch_version: #TODO: remove or replace with boolean to control
        description: "Patch Version Override - e.g. '999'"
        type: string
      distribute:
        description: "Distribute to TestFlight"
        type: boolean
        default: true
      xcode-version:
          description: "Xcode Version Override - e.g. '15.2'"
          type: string

jobs:
  version:
    name: Calculate Version Name and Number
    uses: bitwarden/ios/.github/workflows/_version.yml@main
    with:
      base_version_number: 2000
      version_name: ${{ inputs.version-name }}
      version_number: ${{ inputs.version-number }}
      patch_version: ${{ inputs.patch_version }}
    secrets: inherit

  build-manual:
    name: Build Manual
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: bitwarden/ios/.github/workflows/_build-any.yml@main
    with:
      environment: ${{ inputs.environment }}
      version-name: ${{ inputs.version-name }}
      version-number: ${{ inputs.version-number }}
      distribute: ${{ inputs.distribute }}
  build-public:
    name: Build CI
    if: ${{ github.event_name == 'push' }}
    uses: bitwarden/ios/.github/workflows/_build-any.yml@main
    strategy:
      matrix:
        env: [bwpm_prod, bwpm_beta]
    with:
      environment: ${{ matrix.env }}
      version-name: "2025.3.0"
      version-number: "${{ github.run_number }}"
      distribute: ${{ inputs.distribute }}
    secrets: inherit
